version: '3.4'

services:
  postgres:
    container_name: course_management_system
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: Course_Management_System
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: